# Generated by Django 3.2.5 on 2022-06-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areadoartista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areadoartista',
            options={'ordering': ['id'], 'verbose_name': 'Área do Artista', 'verbose_name_plural': 'Áreas do Artista'},
        ),
    ]
