# Generated by Django 3.2.5 on 2022-06-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areadoartista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArtistaAreadoartista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('areadoartista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areadoartista.areadoartista')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artistas.artista')),
            ],
            options={
                'verbose_name': 'Item da Área do Artista',
                'verbose_name_plural': 'Itens das Áreas do Artista',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='artista',
            name='areadoartista',
            field=models.ManyToManyField(blank=True, through='artistas.ArtistaAreadoartista', to='areadoartista.Areadoartista'),
        ),
    ]
