# Generated by Django 3.2.5 on 2022-06-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='areadoartista',
            new_name='artista_areadoartista',
        ),
    ]
