# Generated by Django 3.2.5 on 2022-06-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0002_auto_20220624_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(max_length=100, verbose_name='Descricao')),
                ('date_fabrication', models.DateField(verbose_name='Data De Pintura')),
                ('is_active', models.BooleanField(default=False, verbose_name='Vivo')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='Foto')),
                ('doc', models.FileField(upload_to='docs', verbose_name='Documentos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.tipo')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['id'],
            },
        ),
    ]
