# Generated by Django 3.2.5 on 2022-06-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tipo',
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ['id'], 'verbose_name': 'tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
